# Generated by Django 3.0.6 on 2020-06-10 14:26
import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('previous', models.CharField(max_length=7)),
                ('number', models.CharField(max_length=2)),
                ('date', models.DateTimeField(default=blog.models.one_minute_hence)),
                ('change_date', models.DateTimeField(
                    default=blog.models.one_day_hence)),
                ('recom', models.CharField(max_length=10)),
                ('success', models.CharField(max_length=7)),
            ],
        ),
    ]
