# Generated by Django 3.0.6 on 2020-06-10 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=2)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
