# Generated by Django 3.0.6 on 2020-06-15 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='recom',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 9, 34, 13, 275740, tzinfo=utc)),
        ),
    ]
