# Generated by Django 3.0.6 on 2020-11-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='recom',
        ),
        migrations.AddField(
            model_name='table',
            name='image',
            field=models.CharField(default='gfgfg', max_length=100000),
            preserve_default=False,
        ),
    ]
