# Generated by Django 3.0.6 on 2020-11-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201112_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='recom',
            field=models.CharField(default='-', max_length=7),
            preserve_default=False,
        ),
    ]
