# Generated by Django 3.0.6 on 2020-06-17 10:44

import blog.models
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200615_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.date),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateTimeField(default=blog.models.one_day_hence),
        ),
    ]
