# Generated by Django 3.0.6 on 2020-11-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_table_recom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='image',
        ),
        migrations.AddField(
            model_name='table',
            name='images',
            field=models.TextField(default='none', max_length=100000000),
            preserve_default=False,
        ),
    ]
