# Generated by Django 3.0.6 on 2020-06-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200617_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='change_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
