# Generated by Django 3.0.6 on 2020-06-17 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200617_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='change_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
