# Generated by Django 3.0.6 on 2020-11-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tableimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableimage',
            name='photo',
            field=models.ImageField(upload_to='static/blog/images'),
        ),
    ]
