# Generated by Django 3.0.6 on 2020-06-17 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200617_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
