# Generated by Django 3.0.6 on 2020-11-14 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201114_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='images',
        ),
        migrations.AddField(
            model_name='tableimage',
            name='firsttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 12, 46, 26, 19152, tzinfo=utc)),
        ),
    ]
