# Generated by Django 3.0.6 on 2020-06-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200617_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='change_date',
        ),
    ]
