# Generated by Django 3.0.6 on 2020-11-14 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201114_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableimage',
            name='recom',
            field=models.TextField(default='jsfkvn', max_length=10000000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tableimage',
            name='firsttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 16, 31, 52, 776790, tzinfo=utc)),
        ),
    ]
