# Generated by Django 3.0.6 on 2020-07-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200619_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='do_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
