# Generated by Django 3.0.6 on 2020-07-17 11:40

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_table_do_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='do_date',
            field=models.DateTimeField(default=blog.models.one_minute_hence),
        ),
    ]
