# Generated by Django 3.0.6 on 2020-08-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_table_do_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='color',
        ),
    ]
