# Generated by Django 3.0.6 on 2020-11-14 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201114_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='stre',
        ),
        migrations.AlterField(
            model_name='tableimage',
            name='firsttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 19, 56, 17, 251490, tzinfo=utc)),
        ),
    ]
