# Generated by Django 3.0.6 on 2020-08-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_table_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='previous',
            field=models.CharField(default='edb', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='success',
            field=models.CharField(default='qwerty', max_length=1),
            preserve_default=False,
        ),
    ]
