# Generated by Django 3.0.6 on 2020-11-15 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201114_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableimage',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 12, 40, 2, 947220, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tableimage',
            name='firsttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 12, 40, 2, 947262, tzinfo=utc)),
        ),
    ]
