# Generated by Django 3.0.6 on 2020-08-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200807_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='success',
            field=models.CharField(max_length=77),
        ),
    ]
