# Generated by Django 3.0.6 on 2021-01-31 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210127_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 1, 31, 10, 22, 18, 880579, tzinfo=utc))),
                ('ime', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.DeleteModel(
            name='Imager',
        ),
        migrations.AddField(
            model_name='tableimage',
            name='im',
            field=models.CharField(default='default', max_length=1000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tableimage',
            name='firsttime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 10, 22, 18, 880208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tableimage',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 10, 22, 18, 880154, tzinfo=utc)),
        ),
    ]
