# Generated by Django 3.0.6 on 2020-08-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200807_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='success',
        ),
    ]
