# Generated by Django 3.0.6 on 2020-08-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_table_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='previous',
        ),
    ]
