# Generated by Django 3.0.6 on 2020-08-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_table_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='success',
            field=models.CharField(default='Qq', max_length=3),
            preserve_default=False,
        ),
    ]
