# Generated by Django 3.0.6 on 2020-08-12 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_table_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='success',
        ),
    ]
