# Generated by Django 3.0.6 on 2020-08-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_table_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='table',
            name='date',
        ),
        migrations.RemoveField(
            model_name='table',
            name='number',
        ),
        migrations.RemoveField(
            model_name='table',
            name='recom',
        ),
        migrations.AddField(
            model_name='table',
            name='da',
            field=models.CharField(default='vfeu', max_length=10),
            preserve_default=False,
        ),
    ]
